### PR TITLE
Fix download path for debian

### PR DESCRIPTION
**Pull request by Olesp**
The download path is with a "-" and not a "_".
This caused a 404 error trying to download the file.

### CODE REVIEW

**Comment by heytrav** [comment]
Do you want to try raising the version to 2.0.4?

**Comment by Olesp** [comment]
> Do you want to try raising the version to 2.0.4?

Yes I am trying to install the latest version available on the download page. I just pasted the link provided.
However I know have an issue when the task create admin is waiting for a connection on the locahost:8086 that never happen.

**Comment by heytrav** [comment]
Yes I realize that. I'm just thinking that raising the version to 2.0.4 might fix the failing tests.

**Comment by heytrav** [comment]
I've checked your branch out and will need to look into why the service doesn't appear to stay running.

**Comment by heytrav** [comment]
The problem was that the config file belonged to the root user and influxd was crashing with a "permission denied" error. It looks like it works ok now that the owner of the config file is being set to "influxdb"

**Pull request merged**
